# -*- coding: utf-8 -*-
"""Data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BqhgoYbNXYHSgENM3w9r62pTHL56UOVN
"""

!pip install requests beautifulsoup4
!pip install vaderSentiment textblob

from google.colab import files
import requests
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
from scipy import stats
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from textblob import TextBlob
import warnings
warnings.filterwarnings("ignore")

"""# Task1: web scraping"""

url = "https://books.toscrape.com/"

response = requests.get(url)

print(response.status_code)

soup = BeautifulSoup(response.text, 'html.parser')

books = soup.find_all('article', class_='product_pod')

print(len(books))

# hardcode
# titles = []
# prices = []

# base_url = "https://books.toscrape.com/catalogue/page-{}.html"

# for page in range(1, 51):   # change 6 to higher later

#     url = base_url.format(page)

#     response = requests.get(url)

#     soup = BeautifulSoup(response.text, 'html.parser')

#     books = soup.find_all('article', class_='product_pod')

#     for book in books:

#         title = book.h3.a['title']

#         price = book.find('p', class_='price_color').text

#         titles.append(title)

#         prices.append(price)

# print(titles[:5])
# print(prices[:5])

# Automatic

titles = []
prices = []
ratings = []

rating_map = {"One":1, "Two":2, "Three":3, "Four":4, "Five":5}

url = "https://books.toscrape.com/catalogue/page-1.html"

while True:
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    books = soup.find_all('article', class_='product_pod')

    for book in books:
        title  = book.h3.a['title']
        price  = float(book.find('p', class_='price_color').text.replace('Â', '').replace('£', '').strip())
        rating = rating_map[book.find('p')['class'][1]]

        titles.append(title)
        prices.append(price)
        ratings.append(rating)

    next_button = soup.find('li', class_='next')
    if next_button:
        next_page = next_button.a['href']
        url = "https://books.toscrape.com/catalogue/" + next_page
    else:
        break

# Save
df = pd.DataFrame({'Title': titles, 'Price (£)': prices, 'Rating (1-5)': ratings})
df.to_csv("books_dataset.csv", index=False)
df.to_excel("books_dataset.xlsx", index=False)

print(f"✅ Scraped {len(df)} books")
print(df.head())

df.to_csv("books_dataset.csv", index=False)
df.to_excel("books_dataset.xlsx", index=False)

files.download("books_dataset.csv")
files.download("books_dataset.xlsx")

"""# TASK 2: Exploratory Data Analysis (EDA) — Books Dataset


"""

# ── 0. Load data ─────────────────────────────────────────────
df = pd.read_excel("books_dataset.xlsx")

print("\n📌 STEP 1 — Data Overview")
print(f"   Shape          : {df.shape[0]} rows × {df.shape[1]} columns")
print(f"   Columns        : {list(df.columns)}")
print("\n   First 5 rows:")
print(df.head().to_string(index=False))

print("\n   Data Types:")
print(df.dtypes)

# ────────────────────────────────────────────────────────────
# STEP 2 — Missing Values & Duplicates
# ────────────────────────────────────────────────────────────
print("\n📌 STEP 2 — Data Quality Check")

missing = df.isnull().sum()
print(f"\n   Missing values:\n{missing}")

dupes = df.duplicated().sum()
print(f"\n   Duplicate rows : {dupes}")

# Drop duplicates if any
df.drop_duplicates(inplace=True)
print(f"   Rows after dedup: {len(df)}")

# ────────────────────────────────────────────────────────────
# STEP 3 — Descriptive Statistics
# ────────────────────────────────────────────────────────────
print("\n📌 STEP 3 — Descriptive Statistics")
print(df.describe().round(2).to_string())

# Extra stats
print(f"\n   Price skewness : {df['Price (£)'].skew():.3f}")
print(f"   Price kurtosis : {df['Price (£)'].kurtosis():.3f}")

# ────────────────────────────────────────────────────────────
# STEP 4 — Rating Distribution
# ────────────────────────────────────────────────────────────
print("\n📌 STEP 4 — Rating Distribution")
rating_counts = df["Rating (1-5)"].value_counts().sort_index()
print(rating_counts)
rating_pct = (rating_counts / len(df) * 100).round(1)
print("\n   % share:")
print(rating_pct)

# ────────────────────────────────────────────────────────────
# STEP 5 — Hypothesis Testing
# ────────────────────────────────────────────────────────────
print("\n📌 STEP 5 — Hypothesis Testing")
# H0: No difference in mean price across rating groups
groups = [df[df["Rating (1-5)"] == r]["Price (£)"].values
          for r in sorted(df["Rating (1-5)"].unique())]
f_stat, p_value = stats.f_oneway(*groups)
print(f"   One-way ANOVA — Price vs Rating:")
print(f"   F-statistic = {f_stat:.4f},  p-value = {p_value:.4f}")
if p_value < 0.05:
    print("   ✅ Significant: price differs across rating groups (p < 0.05)")
else:
    print("   ❌ Not significant: no strong price-rating relationship (p ≥ 0.05)")

# Correlation
corr, corr_p = stats.pearsonr(df["Price (£)"], df["Rating (1-5)"])
print(f"\n   Pearson correlation (Price vs Rating):")
print(f"   r = {corr:.4f},  p = {corr_p:.4f}")

# ────────────────────────────────────────────────────────────
# STEP 6 — Price analysis per rating bucket
# ────────────────────────────────────────────────────────────
print("\n📌 STEP 6 — Mean Price per Rating")
mean_price = df.groupby("Rating (1-5)")["Price (£)"].agg(["mean", "median", "std"]).round(2)
print(mean_price)

print("\n📌 STEP 7 — Price Buckets")
df["Price Bucket"] = pd.cut(df["Price (£)"],
                             bins=[0, 15, 30, 45, 60],
                             labels=["£0-15", "£15-30", "£30-45", "£45-60"])
print(df["Price Bucket"].value_counts())

print("\n✅ EDA complete. Run task3_visualization.py to see charts.")

"""# Task3: Visualization"""

# Add price bucket column
df["Price Bucket"] = pd.cut(df["Price (£)"],
                             bins=[0, 15, 30, 45, 60],
                             labels=["£0-15", "£15-30", "£30-45", "£45-60"])

# Colour palette
PALETTE = sns.color_palette("Set2", 5)
sns.set_theme(style="whitegrid", font_scale=1.1)

# ────────────────────────────────────────────────────────────
# CHART 1 — Rating Distribution (bar chart)
# ────────────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(8, 5))
rating_counts = df["Rating (1-5)"].value_counts().sort_index()
bars = ax.bar(rating_counts.index, rating_counts.values,
              color=PALETTE, edgecolor="white", linewidth=1.5)

for bar, val in zip(bars, rating_counts.values):
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 2,
            str(val), ha="center", va="bottom", fontweight="bold")

ax.set_title("Distribution of Book Ratings", fontsize=15, fontweight="bold", pad=15)
ax.set_xlabel("Star Rating (1 = Worst, 5 = Best)")
ax.set_ylabel("Number of Books")
ax.set_xticks([1, 2, 3, 4, 5])
plt.tight_layout()
plt.savefig("chart1_rating_distribution.png", dpi=150)
plt.show()
plt.close()
print("✅ chart1_rating_distribution.png saved")

# ────────────────────────────────────────────────────────────
# CHART 2 — Price Distribution (histogram + KDE)
# ────────────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(9, 5))
sns.histplot(df["Price (£)"], bins=25, kde=True, color="#4C9BE8",
             edgecolor="white", ax=ax, line_kws={"linewidth": 2})

ax.axvline(df["Price (£)"].mean(), color="red", linestyle="--",
           linewidth=1.8, label=f'Mean £{df["Price (£)"].mean():.2f}')
ax.axvline(df["Price (£)"].median(), color="orange", linestyle="--",
           linewidth=1.8, label=f'Median £{df["Price (£)"].median():.2f}')

ax.set_title("Price Distribution of Books", fontsize=15, fontweight="bold", pad=15)
ax.set_xlabel("Price (£)")
ax.set_ylabel("Count")
ax.legend()
plt.tight_layout()
plt.savefig("chart2_price_distribution.png", dpi=150)
plt.show()
plt.close()
print("✅ chart2_price_distribution.png saved")

# ────────────────────────────────────────────────────────────
# CHART 3 — Boxplot: Price by Rating
# ────────────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(9, 5))
sns.boxplot(data=df, x="Rating (1-5)", y="Price (£)",
            palette="Set2", linewidth=1.5, ax=ax)

ax.set_title("Price Spread by Star Rating", fontsize=15, fontweight="bold", pad=15)
ax.set_xlabel("Star Rating")
ax.set_ylabel("Price (£)")
plt.tight_layout()
plt.savefig("chart3_price_by_rating_boxplot.png", dpi=150)
plt.show()
plt.close()
print("✅ chart3_price_by_rating_boxplot.png saved")

# ────────────────────────────────────────────────────────────
# CHART 4 — Mean Price per Rating (line + dot)
# ────────────────────────────────────────────────────────────
mean_price = df.groupby("Rating (1-5)")["Price (£)"].mean()

fig, ax = plt.subplots(figsize=(8, 5))
ax.plot(mean_price.index, mean_price.values,
        marker="o", linewidth=2.5, markersize=9, color="#E85D75")

for x, y in zip(mean_price.index, mean_price.values):
    ax.annotate(f"£{y:.2f}", (x, y),
                textcoords="offset points", xytext=(0, 12),
                ha="center", fontsize=10, fontweight="bold")

ax.set_title("Average Price by Star Rating", fontsize=15, fontweight="bold", pad=15)
ax.set_xlabel("Star Rating")
ax.set_ylabel("Average Price (£)")
ax.set_xticks([1, 2, 3, 4, 5])
ax.set_ylim(0, mean_price.max() + 10)
plt.tight_layout()
plt.savefig("chart4_avg_price_per_rating.png", dpi=150)
plt.show()
plt.close()
print("✅ chart4_avg_price_per_rating.png saved")

# ────────────────────────────────────────────────────────────
# CHART 5 — Price Bucket vs Rating (stacked bar)
# ────────────────────────────────────────────────────────────
pivot = df.groupby(["Price Bucket", "Rating (1-5)"]).size().unstack(fill_value=0)

fig, ax = plt.subplots(figsize=(10, 6))
pivot.plot(kind="bar", stacked=True, colormap="Set2",
           edgecolor="white", linewidth=0.8, ax=ax)

ax.set_title("Rating Spread Within Price Buckets", fontsize=15, fontweight="bold", pad=15)
ax.set_xlabel("Price Bucket")
ax.set_ylabel("Number of Books")
ax.set_xticklabels(ax.get_xticklabels(), rotation=0)
ax.legend(title="Stars", bbox_to_anchor=(1.01, 1), loc="upper left")
plt.tight_layout()
plt.savefig("chart5_price_bucket_rating_stacked.png", dpi=150)
plt.show()
plt.close()
print("✅ chart5_price_bucket_rating_stacked.png saved")

# ────────────────────────────────────────────────────────────
# CHART 6 — Scatter: Price vs Rating (jittered)
# ────────────────────────────────────────────────────────────
jitter = np.random.uniform(-0.2, 0.2, size=len(df))

fig, ax = plt.subplots(figsize=(9, 5))
sc = ax.scatter(df["Rating (1-5)"] + jitter, df["Price (£)"],
                alpha=0.35, c=df["Rating (1-5)"],
                cmap="Set2", edgecolors="none", s=40)

# Trend line
m, b = np.polyfit(df["Rating (1-5)"], df["Price (£)"], 1)
x_line = np.linspace(1, 5, 100)
ax.plot(x_line, m * x_line + b, color="red", linewidth=2,
        linestyle="--", label=f"Trend (slope={m:.2f})")

ax.set_title("Price vs Rating (Jittered Scatter)", fontsize=15, fontweight="bold", pad=15)
ax.set_xlabel("Star Rating")
ax.set_ylabel("Price (£)")
ax.set_xticks([1, 2, 3, 4, 5])
ax.legend()
plt.tight_layout()
plt.savefig("chart6_scatter_price_vs_rating.png", dpi=150)
plt.show()
plt.close()
print("✅ chart6_scatter_price_vs_rating.png saved")

# ────────────────────────────────────────────────────────────
# DASHBOARD — all 6 charts in one figure
# ────────────────────────────────────────────────────────────
fig = plt.figure(figsize=(20, 22))
gs  = gridspec.GridSpec(3, 2, figure=fig, hspace=0.45, wspace=0.35)

CHART_FILES = [
    "chart1_rating_distribution.png",
    "chart2_price_distribution.png",
    "chart3_price_by_rating_boxplot.png",
    "chart4_avg_price_per_rating.png",
    "chart5_price_bucket_rating_stacked.png",
    "chart6_scatter_price_vs_rating.png",
]

import matplotlib.image as mpimg

for i, path in enumerate(CHART_FILES):
    ax = fig.add_subplot(gs[i // 2, i % 2])
    img = mpimg.imread(path)
    ax.imshow(img)
    ax.axis("off")

fig.suptitle("📚 Books to Scrape — Data Visualization Dashboard",
             fontsize=22, fontweight="bold", y=0.98)
plt.savefig("dashboard.png", dpi=150, bbox_inches="tight")
plt.show()
plt.close()
print("\n✅ dashboard.png saved — all 6 charts combined!")
print("\n🎉 Task 3 complete. Check the PNG files in this folder.")

# To download all the charts

# files.download("chart1_rating_distribution.png")
# files.download("chart2_price_distribution.png")
# files.download("chart3_price_by_rating_boxplot.png")
# files.download("chart4_avg_price_per_rating.png")
# files.download("chart5_price_bucket_rating_stacked.png")
# files.download("chart6_scatter_price_vs_rating.png")
# files.download("dashboard.png")

"""# Task4 sentiment analysis

"""

# ────────────────────────────────────────────────────────────
# STEP 1 — VADER Sentiment (compound score, -1 to +1)
# ────────────────────────────────────────────────────────────
print("\n📌 STEP 1 — Running VADER on titles …")
analyzer = SentimentIntensityAnalyzer()

def vader_scores(text):
    s = analyzer.polarity_scores(str(text))
    return s["neg"], s["neu"], s["pos"], s["compound"]

df[["VADER_neg", "VADER_neu", "VADER_pos", "VADER_compound"]] = df["Title"].apply(
    lambda t: pd.Series(vader_scores(t))
)

# Classify: compound >= 0.05 → Positive, <= -0.05 → Negative, else Neutral
def vader_label(compound):
    if compound >= 0.05:
        return "Positive"
    elif compound <= -0.05:
        return "Negative"
    return "Neutral"

df["VADER_Sentiment"] = df["VADER_compound"].apply(vader_label)
print(df["VADER_Sentiment"].value_counts())

# ────────────────────────────────────────────────────────────
# STEP 2 — TextBlob Sentiment (polarity -1 to +1, subjectivity 0 to 1)
# ────────────────────────────────────────────────────────────
print("\n📌 STEP 2 — Running TextBlob on titles …")

def textblob_scores(text):
    blob = TextBlob(str(text))
    return blob.sentiment.polarity, blob.sentiment.subjectivity

df[["TB_polarity", "TB_subjectivity"]] = df["Title"].apply(
    lambda t: pd.Series(textblob_scores(t))
)

def textblob_label(polarity):
    if polarity > 0.05:
        return "Positive"
    elif polarity < -0.05:
        return "Negative"
    return "Neutral"

df["TB_Sentiment"] = df["TB_polarity"].apply(textblob_label)
print(df["TB_Sentiment"].value_counts())

# ────────────────────────────────────────────────────────────
# STEP 3 — Agreement between the two models
# ────────────────────────────────────────────────────────────
print("\n📌 STEP 3 — Model Agreement")
df["Models_Agree"] = df["VADER_Sentiment"] == df["TB_Sentiment"]
agree_pct = df["Models_Agree"].mean() * 100
print(f"   Models agree on {agree_pct:.1f}% of titles")

# ────────────────────────────────────────────────────────────
# STEP 4 — Sentiment vs Star Rating
# ────────────────────────────────────────────────────────────
print("\n📌 STEP 4 — VADER Compound Score by Star Rating")
avg_sentiment = df.groupby("Rating (1-5)")["VADER_compound"].mean().round(3)
print(avg_sentiment)

# ────────────────────────────────────────────────────────────
# STEP 5 — Most Positive / Negative titles
# ────────────────────────────────────────────────────────────
print("\n📌 STEP 5 — Top 5 Most POSITIVE titles (VADER)")
top_pos = df.nlargest(5, "VADER_compound")[["Title", "VADER_compound", "Rating (1-5)"]]
print(top_pos.to_string(index=False))

print("\n📌 Top 5 Most NEGATIVE titles (VADER)")
top_neg = df.nsmallest(5, "VADER_compound")[["Title", "VADER_compound", "Rating (1-5)"]]
print(top_neg.to_string(index=False))

# ────────────────────────────────────────────────────────────
# STEP 6 — Visualizations
# ────────────────────────────────────────────────────────────
sns.set_theme(style="whitegrid", font_scale=1.1)
PALETTE = {"Positive": "#55A868", "Neutral": "#8DA0CB", "Negative": "#E24A33"}

# 6a — VADER sentiment breakdown (pie)
fig, axes = plt.subplots(1, 2, figsize=(13, 5))
vader_counts = df["VADER_Sentiment"].value_counts()
axes[0].pie(vader_counts, labels=vader_counts.index,
            colors=[PALETTE[l] for l in vader_counts.index],
            autopct="%1.1f%%", startangle=140,
            wedgeprops={"edgecolor": "white", "linewidth": 2})
axes[0].set_title("VADER Sentiment Distribution\n(Book Titles)", fontweight="bold")

# 6b — Compound score distribution
sns.histplot(df["VADER_compound"], bins=30, kde=True,
             color="#4C9BE8", edgecolor="white", ax=axes[1])
axes[1].axvline(0.05, color="green", linestyle="--", label="Pos threshold")
axes[1].axvline(-0.05, color="red", linestyle="--", label="Neg threshold")
axes[1].set_title("VADER Compound Score Distribution", fontweight="bold")
axes[1].set_xlabel("Compound Score")
axes[1].legend()

plt.tight_layout()
plt.savefig("sentiment_chart1_overview.png", dpi=150)
plt.show()
plt.close()
print("\n✅ sentiment_chart1_overview.png saved")

# 6c — Sentiment by star rating (heatmap)
heatmap_data = df.groupby(["Rating (1-5)", "VADER_Sentiment"]).size().unstack(fill_value=0)
fig, ax = plt.subplots(figsize=(8, 4))
sns.heatmap(heatmap_data, annot=True, fmt="d", cmap="Blues",
            linewidths=0.5, linecolor="white", ax=ax)
ax.set_title("Sentiment Count by Star Rating", fontweight="bold", pad=15)
ax.set_xlabel("Sentiment Label")
ax.set_ylabel("Star Rating")
plt.tight_layout()
plt.savefig("sentiment_chart2_heatmap.png", dpi=150)
plt.show()
plt.close()
print("✅ sentiment_chart2_heatmap.png saved")
# 6d — VADER compound score by rating (violin)
fig, ax = plt.subplots(figsize=(9, 5))
sns.violinplot(data=df, x="Rating (1-5)", y="VADER_compound",
               palette="Set2", inner="box", ax=ax)
ax.axhline(0, color="red", linestyle="--", linewidth=1.2, label="Neutral line")
ax.set_title("VADER Compound Score Distribution by Rating", fontweight="bold", pad=15)
ax.set_xlabel("Star Rating")
ax.set_ylabel("Compound Score")
ax.legend()
plt.tight_layout()
plt.savefig("sentiment_chart3_violin.png", dpi=150)
plt.show()
plt.close()
print("✅ sentiment_chart3_violin.png saved")

# ────────────────────────────────────────────────────────────
# STEP 7 — Save enriched dataset
# ────────────────────────────────────────────────────────────
output_cols = [
    "Title", "Price (£)", "Rating (1-5)",
    "VADER_compound", "VADER_Sentiment",
    "TB_polarity", "TB_subjectivity", "TB_Sentiment",
    "Models_Agree"
]
df[output_cols].to_excel("sentiment_results.xlsx", index=False)
df[output_cols].head(20)
print("\n📁 sentiment_results.xlsx saved with all sentiment scores.")
print("\n🎉 Task 4 complete!")

#files.download("sentiment_results.xlsx")